### ISSUE TITLE
RDK deploying empty rule

### ISSUE THREAD

**Issue by 5u5hma** [awslabs/aws-config-rdk#42]
RDK was deploying even when I gave a wrong rule name
So I gave MFARule instead of MFArule it successfully deployed it but later evaluation did not work.
But if it gets deployed you will never know if you provided wrong rule name or not

**Comment by michaelborchert** [comment]
Thanks or catching this!  I'll add a check to make sure the rule directory exists before trying to deploy.

**Comment by michaelborchert** [comment]
I've merged in a PR with a fix for this, and will push a new version up to pypi along with some other changes in a few days.

**Comment by 5u5hma** [comment]
Thank you.

Will keep an eye on the new release and will update accordingly when using
it further.

**Comment by michaelborchert** [comment]
This should be fixed now in the version available on PyPi.  Thanks!

**Comment by rafihm** [comment]
I think we still have this issue.

```
$ pip freeze | grep rdk
rdk==0.3.18
```

Using the latest version of the rdk (0.3.18)
got the below error

```
$ rdk deploy
Running deploy!
Traceback (most recent call last):
  File "/usr/local/bin/rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 58, in process_command
    exit_code = method_to_call()
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 448, in deploy
    rule_names = self.__get_rule_list_for_command()
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 1113, in __get_rule_list_for_command
    cleaned_rule_name = self.__clean_rule_name(self.args.rulename[0])
IndexError: list index out of range
```
